import mongoose from "mongoose";

const notificationSchema = new mongoose.Schema(
  {
    user: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "User", 
      required: true 
    },
    title: { 
      type: String, 
      required: true 
    },
    message: { 
      type: String 
    },
    type: {
      type: String,
      enum: ["assignment", "video", "module", "course", "project", "info", "alert", "system"],
      default: "info",
    },
    link: {
      type: String // URL or route for the notification
    },
    read: { 
      type: Boolean, 
      default: false 
    },
    manual: {
      type: Boolean,
      default: false
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User"
    },
    autoGenerated: {
      type: Boolean,
      default: false
    }
  },
  { timestamps: true }
);

export default mongoose.model("Notification", notificationSchema);