// services/notificationService.js
import Notification from "../models/Notification.js";
// services/notificationService.js
const allowedTypes = ["course", "section", "module", "assignment", "project", "quiz", "support"];

export const createNotificationForUser = async ({ userId, title, message, type, link }) => {
  if (!userId || !title) throw new Error("User and title are required");
  if (!allowedTypes.includes(type)) throw new Error(`Invalid notification type: ${type}`);

  const notification = new Notification({
    user: userId,
    title,
    message,
    type,
    link,
    autoGenerated: true
  });

  console.log("📝 Creating notification:", notification);
  return await notification.save();
};